from big_ol_pile_of_manim_imports import *
from extract_scene import*

class mth(Scene):
    def construct(self):
        t0 = TextMobject("计算")
        d1 = TexMobject("\dfrac{\sqrt{\dfrac{1}{1329409}}}{\dfrac{1}{1329409}")
        d2 = TexMobject("\dfrac{\sqrt{ }}{1}")
        d3 = TexMobject("\sqrt{ }")
        t1 = TexMobject("\\scriptsize{\\text{由于根号的英文是 radical sign,将它的各个字母的 ASCII 值加起来就能得到}}")
        d4 = TexMobject("\\scriptsize{\\text{114+97+100+105+99+97+108+115+105+103+110=1153}}")
        t2 = TexMobject("\\text{所以 }\dfrac{\sqrt{\dfrac{1}{1329409}}}{\dfrac{1}{1329409}} = \sqrt{ } = 1153")
        t3 = TexMobject("\\text{约去分子分母中的 }\dfrac{1}{1329409}")
        t0.to_corner(UP+LEFT)
        self.play(FadeIn(t0, shift=LEFT))
        self.play(Write(d1))
        self.wait()
        self.wait()
        self.play(FadeOut(t0, shift=LEFT))
        t3.to_corner(UP+LEFT)
        self.play(FadeIn(t3, shift=LEFT),ReplacementTransform(d1, d2),)
        self.wait()
        self.wait()
        self.play(ReplacementTransform(d2, d3),)
        self.wait()
        self.wait()
        t1.to_corner(UP+LEFT)
        self.play(FadeOut(t3, shift=LEFT), Uncreate(d3), FadeIn(t1, shift=UP))
        self.wait()
        self.wait()
        self.play(Write(d4))
        self.wait()
        self.wait()
        self.play(Uncreate(t1), ReplacementTransform(d4, t2),)
        self.wait()
        self.wait()
        self.play(Uncreate(t2))
        
        t1 = TextMobject("证明")
        d1 = TexMobject("1!=1\\text{ 是假命题}")
        t2 = TexMobject("\\scriptsize{\\text{因为在 C/C++/Python 等编程语言中,符号 != 表示为不等于，所以上式可以化为}}")
        d2 = TexMobject("1 \\ne 1")
        t3 = TextMobject("很明显,1 不可能不等于自身,所以 1!=1\\text{ 是假命题.}")
        t4 = TexMobject("\\text{QED.}")
        t1.to_corner(UP+LEFT)
        self.play(FadeIn(t1, shift=LEFT))
        self.play(Write(d1))
        self.wait()
        self.wait()
        t2.to_corner(UP+LEFT)
        self.play(FadeOut(t1, shift=LEFT), FadeIn(t2, shift=LEFT), ReplacementTransform(d1, d2),)
        self.wait()
        self.wait()
        t4.to_corner(DOWN+RIGHT)
        self.play(FadeOut(t2, shift=LEFT),ReplacementTransform(d2, t3),FadeIn(t4, shift = RIGHT))
        self.wait()
        self.wait()
        self.play(Uncreate(t3), Uncreate(t4))
        self.wait()
        self.wait()

        t0 = TextMobject("计算")
        d1 = TexMobject("\dfrac{\mathrm d}{\mathrm dx}x")
        d2 = TexMobject("\dfrac{\mathrm dx}{\mathrm dx}")
        d3 = TexMobject("\dfrac{\mathrm dx}{\mathrm dx} = 1")
        t1 = TextMobject("上式可以化为")
        t2 = TextMobject("约去分子分母")
        t0.to_corner(UP+LEFT)
        self.play(FadeIn(t0, shift=LEFT))
        self.play(Write(d1))
        self.wait()
        self.wait()
        self.play(FadeOut(t0, shift=LEFT))
        t1.to_corner(UP+LEFT)
        self.wait()
        self.wait()
        self.play(FadeIn(t1, shift=LEFT),ReplacementTransform(d1, d2),)
        self.wait()
        self.wait()
        self.play(FadeOut(t1, shift=LEFT))
        t2.to_corner(UP+LEFT)
        self.wait()
        self.wait()
        self.play(FadeIn(t2, shift=LEFT),ReplacementTransform(d2, d3),)
        self.wait()
        self.wait()
        self.play(FadeOut(t2, shift=LEFT))
        self.wait()
        self.wait()
        self.play(Uncreate(d3))

        t1 = TextMobject("计算")
        d1 = TexMobject("\sin 114514^{\circ} + \sin 1919810^{\circ} + \sin 137486^{\circ}")
        t2 = TextMobject("上式可化为")
        d2 = TexMobject("\sin (114514^{\circ} + 1919810^{\circ} + 137486^{\circ})")
        d3 = TexMobject("\sin 2171810^{\circ}")
        t3 = TexMobject("\\text{由 }\sin(\\alpha + k \\times 2\pi)=\sin \\alpha \\text{ 得}")
        d4 = TexMobject("\sin 2171810^{\circ}=\sin (2171810^{\circ} \\bmod 360^{\circ}) = \sin 290^{\circ}")
        t4 = TexMobject("\\text{由 }\sin(\\alpha + \pi)=-\sin \\alpha \\text{ 得}")
        d5 = TexMobject("\sin 290^{\circ} = -\sin 70^{\circ}")
        t5 = TextMobject("则有")
        d6 = TexMobject("-\sin 70^{\circ} = -\dfrac{\sqrt[3]{\dfrac{1+\sqrt{3}i}{2}}+\sqrt[3]{\dfrac{1-\sqrt{3}i}{2}}}{2}\\approx -0.939")
        t1.to_corner(UP+LEFT)
        self.play(FadeIn(t1, shift=LEFT))
        self.play(Write(d1))
        self.wait()
        self.wait()
        t2.to_corner(UP+LEFT)
        self.play(FadeOut(t1, shift = LEFT), FadeIn(t2, shift = LEFT), ReplacementTransform(d1, d2),)
        self.wait()
        self.wait()
        self.play(ReplacementTransform(d2, d3),)
        self.wait()
        self.wait()
        t3.to_corner(UP+LEFT)
        self.play(FadeOut(t2, shift = LEFT), FadeIn(t3, shift = LEFT), ReplacementTransform(d3, d4),)
        self.wait()
        self.wait()
        t4.to_corner(UP+LEFT)
        self.play(FadeOut(t3, shift = LEFT), FadeIn(t4, shift = LEFT), ReplacementTransform(d4, d5),)
        self.wait()
        self.wait()
        t5.to_corner(UP+LEFT)
        self.play(FadeOut(t4, shift = LEFT), FadeIn(t5, shift = LEFT), ReplacementTransform(d5, d6),)
        self.wait()
        self.wait()
        self.play(Uncreate(t5), Uncreate(d6))
        self.wait()
        self.wait()

        t1 = TextMobject("证明")
        d1 = TexMobject("\displaystyle\lim_{x\\rightarrow0}\dfrac{\\tan x}{x}=1")
        t2 = TexMobject("\\text{设 }x = 0,\\text{则有}")
        d2 = TexMobject("\dfrac{\\tan x}{x} = \dfrac{\\tan 0}{0} = \dfrac{0}{0}")
        t3 = TextMobject("约分,得")
        d3 = TexMobject("\dfrac{0}{0} = 1")
        t4 = TextMobject("所以")
        t5 = TexMobject("\\text{QED.}")
        d4 = TexMobject("\displaystyle\lim_{x\\rightarrow0}\dfrac{\\tan x}{x}=1")
        t1.to_corner(UP+LEFT)
        self.play(FadeIn(t1, shift=LEFT))
        self.play(Write(d1))
        self.wait()
        self.wait()
        t2.to_corner(UP+LEFT)
        self.play(FadeOut(t1, shift = LEFT), FadeIn(t2, shift = LEFT), ReplacementTransform(d1, d2))
        self.wait()
        self.wait()
        t3.to_corner(UP+LEFT)
        self.play(FadeOut(t2, shift = LEFT), FadeIn(t3, shift = LEFT), ReplacementTransform(d2, d3),)
        self.wait()
        self.wait()
        t4.to_corner(UP+LEFT)
        t5.to_corner(DOWN+RIGHT)
        self.play(FadeOut(t3, shift = LEFT), FadeIn(t4, shift = LEFT), ReplacementTransform(d3, d4),FadeIn(t5, shift = RIGHT))
        self.wait()
        self.wait()
        self.play(Uncreate(d4), Uncreate(t5))
        self.wait()
        self.wait()    
